data:
  arjuna_options:
    app.url: http://run

  user_options:
    roption: 1


data1:
  arjuna_options:
    browser.name: firefox
    app.url: https://data1

  user_options:
    user: data1_user
    check: data1

data2:
  arjuna_options:
    browser.name: chrome
    app.url: https://data2

  user_options:
    user: data2_user
    check: data2