gp1:
  conf: data1_env1
  imod:
    - check_group_info_1

gp2:
  conf: data2_env2
  im:
    - check_group_info_2

gp3:
  conf: data1_env1
  im:
    - check_group_info_1

gp4:
  conf: data2_env2
  im:
    - check_group_info_2

gp_tag:

  ir:
    - "with tags slow"

gp_rules:

  conf: data2_env2

  ir:
    - "package *= data"

  er:
    - "module !*= excel"

check_conf:
  conf: firefox

  im:
    - check_group_conf
    - check_01_simple_test

all_gp1:
  conf: chrome

  ir:
    - "package *= pkg"

all_gp2:
  conf: firefox

  ir:
    - "package *= pkg"


    